services:
  - type: web
    name: athaanfibeit-livepage
    env: node
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://shaheentoefy:GevqhNbFMrypZ3Ru@cluster0.tliyoy3.mongodb.net/athaan?retryWrites=true&w=majority&appName=Cluster0
      - key: EMAIL_USER
        value: "PLACEHOLDER"
      - key: EMAIL_PASS
        value: "PLACEHOLDER"
      - key: ADMIN_EMAIL
        value: "PLACEHOLDER"
      - key: RECAPTCHA_SECRET
        value: "PLACEHOLDER"
