services:
  - type: web
    name: athaanfibeit-livepage
    env: node
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
      - key: EMAIL_USER
      - key: EMAIL_PASS
      - key: ADMIN_EMAIL
      - key: RECAPTCHA_SECRET
